// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThongKe.Data.Models;

namespace ThongKe.Migrations
{
    [DbContext(typeof(thongkeContext))]
    [Migration("20200212042351_changeDateToNullable")]
    partial class changeDateToNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThongKe.Data.Models.Chinhanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Chinhanh1")
                        .IsRequired()
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Diachi")
                        .HasColumnName("diachi")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Dienthoai")
                        .HasColumnName("dienthoai")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Masothue")
                        .HasColumnName("masothue")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nhom")
                        .HasColumnName("nhom")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Tencn")
                        .HasColumnName("tencn")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Thanhpho")
                        .HasColumnName("thanhpho")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<bool?>("Trangthai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trangthai")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("chinhanh");
                });

            modelBuilder.Entity("ThongKe.Data.Models.Chitiettour", b =>
                {
                    b.Property<string>("Sgtcode")
                        .HasColumnName("sgtcode")
                        .HasColumnType("varchar(17)")
                        .HasMaxLength(17)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Batdau")
                        .HasColumnName("batdau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Ketthuc")
                        .HasColumnName("ketthuc")
                        .HasColumnType("datetime");

                    b.Property<string>("Tuyentq")
                        .HasColumnName("tuyentq")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.HasKey("Sgtcode");

                    b.ToTable("chitiettour");
                });

            modelBuilder.Entity("ThongKe.Data.Models.Dmdaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Daily")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Dienthoai")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TenDaily")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("Trangthai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trangthai")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.ToTable("dmdaily");
                });

            modelBuilder.Entity("ThongKe.Data.Models.DoanThuDoanNgayDi", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Dailyxuatve")
                        .HasColumnName("dailyxuatve")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Doanhso")
                        .HasColumnName("doanhso")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Doanhthu")
                        .HasColumnName("doanhthu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Sokhach")
                        .HasColumnName("sokhach")
                        .HasColumnType("int");

                    b.HasKey("Stt")
                        .HasName("PK_doanthuQuayNgayBan_1");

                    b.ToTable("doanthuQuayNgayBan");
                });

            modelBuilder.Entity("ThongKe.Data.Models.DoanhthuDoanChitiet", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Congno")
                        .HasColumnName("congno")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Diachi")
                        .HasColumnName("diachi")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Diemdon")
                        .HasColumnName("diemdon")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Ghichu")
                        .HasColumnName("ghichu")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal?>("Giave")
                        .HasColumnName("giave")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Serial")
                        .HasColumnName("serial")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int?>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("int");

                    b.Property<string>("Tenkhach")
                        .HasColumnName("tenkhach")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal?>("Thucthu")
                        .HasColumnName("thucthu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Vetourid")
                        .HasColumnName("vetourid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("doanhthuDoanChitiet");
                });

            modelBuilder.Entity("ThongKe.Data.Models.DoanhthuDoanNgayDi", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Batdau")
                        .HasColumnName("batdau")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Doanhthu")
                        .HasColumnName("doanhthu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("Ketthuc")
                        .HasColumnName("ketthuc")
                        .HasColumnType("datetime");

                    b.Property<string>("Sgtcode")
                        .HasColumnName("sgtcode")
                        .HasColumnType("varchar(17)")
                        .HasMaxLength(17)
                        .IsUnicode(false);

                    b.Property<int?>("Sokhach")
                        .HasColumnName("sokhach")
                        .HasColumnType("int");

                    b.Property<string>("Tuyentq")
                        .HasColumnName("tuyentq")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Stt");

                    b.ToTable("doanhthuDoanNgayDi");
                });

            modelBuilder.Entity("ThongKe.Data.Models.DoanhthuQuayChitiet", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<decimal?>("Giave")
                        .HasColumnName("giave")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Hanhtrinh")
                        .HasColumnName("hanhtrinh")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Ngaydi")
                        .HasColumnName("ngaydi")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Ngayve")
                        .HasColumnName("ngayve")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Nguoiban")
                        .HasColumnName("nguoiban")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Serial")
                        .HasColumnName("serial")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Sgtcode")
                        .HasColumnName("sgtcode")
                        .HasColumnType("varchar(17)")
                        .HasMaxLength(17)
                        .IsUnicode(false);

                    b.Property<int>("Sokhach")
                        .HasColumnName("sokhach")
                        .HasColumnType("int");

                    b.Property<string>("Tenkhach")
                        .HasColumnName("tenkhach")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Stt");

                    b.ToTable("doanhthuQuayChitiet");
                });

            modelBuilder.Entity("ThongKe.Data.Models.DoanhthuSaleChitiet", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<int?>("Chiemcho")
                        .HasColumnName("chiemcho")
                        .HasColumnType("int");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<decimal?>("Doanhthu")
                        .HasColumnName("doanhthu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Nguoixuatve")
                        .HasColumnName("nguoixuatve")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Sgtcode")
                        .HasColumnName("sgtcode")
                        .HasColumnType("varchar(17)")
                        .HasMaxLength(17)
                        .IsUnicode(false);

                    b.Property<string>("Tenkhach")
                        .HasColumnName("tenkhach")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Thucthu")
                        .HasColumnName("thucthu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Tuyentq")
                        .HasColumnName("tuyentq")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Stt")
                        .HasName("PK_doanhthusalechitiet");

                    b.ToTable("doanhthuSaleChitiet");
                });

            modelBuilder.Entity("ThongKe.Data.Models.DoanhthuSaleQuay", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<decimal?>("Doanhso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("doanhso")
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Nguoixuatve")
                        .HasColumnName("nguoixuatve")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Thucthu")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("thucthu")
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Stt");

                    b.ToTable("doanhthuSaleQuay");
                });

            modelBuilder.Entity("ThongKe.Data.Models.DoanhthuSaleTuyen", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<decimal?>("Doanhso")
                        .HasColumnName("doanhso")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Nguoixuatve")
                        .HasColumnName("nguoixuatve")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Thucthu")
                        .HasColumnName("thucthu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Tuyentq")
                        .HasColumnName("tuyentq")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Stt");

                    b.ToTable("doanhthuSaleTuyen");
                });

            modelBuilder.Entity("ThongKe.Data.Models.DoanhthuSaleTuyentqChitiet", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<int?>("Chiemcho")
                        .HasColumnName("chiemcho")
                        .HasColumnType("int");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<decimal?>("Doanhthu")
                        .HasColumnName("doanhthu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Nguoixuatve")
                        .HasColumnName("nguoixuatve")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Sgtcode")
                        .HasColumnName("sgtcode")
                        .HasColumnType("varchar(17)")
                        .HasMaxLength(17)
                        .IsUnicode(false);

                    b.Property<string>("Tenkhach")
                        .HasColumnName("tenkhach")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Thucthu")
                        .HasColumnName("thucthu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Tuyentq")
                        .HasColumnName("tuyentq")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Stt");

                    b.ToTable("doanhthuSaleTuyentqChitiet");
                });

            modelBuilder.Entity("ThongKe.Data.Models.DoanhthuToanhethong", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Dailyxuatve")
                        .HasColumnName("dailyxuatve")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Khachcu")
                        .HasColumnName("khachcu")
                        .HasColumnType("int");

                    b.Property<int?>("Khachht")
                        .HasColumnName("khachht")
                        .HasColumnType("int");

                    b.Property<decimal?>("Thucthucu")
                        .HasColumnName("thucthucu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Thucthuht")
                        .HasColumnName("thucthuht")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Stt")
                        .HasName("PK_doanhthuToanhethong_1");

                    b.ToTable("doanhthuToanhethong");
                });

            modelBuilder.Entity("ThongKe.Data.Models.QuayNgayBan", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Dailyxuatve")
                        .HasColumnName("dailyxuatve")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Doanhso")
                        .HasColumnName("doanhso")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Doanhthu")
                        .HasColumnName("doanhthu")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Sokhach")
                        .HasColumnName("sokhach")
                        .HasColumnType("int");

                    b.HasKey("Stt");

                    b.ToTable("QuayNgayBan");
                });

            modelBuilder.Entity("ThongKe.Data.Models.Thongkeweb", b =>
                {
                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int?>("Chuaxuatve")
                        .HasColumnName("chuaxuatve")
                        .HasColumnType("int");

                    b.Property<int?>("Huy")
                        .HasColumnName("huy")
                        .HasColumnType("int");

                    b.Property<int?>("Taove")
                        .HasColumnName("taove")
                        .HasColumnType("int");

                    b.Property<int?>("Thanhcong")
                        .HasColumnName("thanhcong")
                        .HasColumnType("int");

                    b.Property<int?>("Tuhuy")
                        .HasColumnName("tuhuy")
                        .HasColumnType("int");

                    b.HasKey("Chinhanh");

                    b.ToTable("thongkeweb");
                });

            modelBuilder.Entity("ThongKe.Data.Models.Thongkewebchitiet", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Dailyxuatve")
                        .HasColumnName("dailyxuatve")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Doanhso")
                        .HasColumnName("doanhso")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Hanhtrinh")
                        .HasColumnName("hanhtrinh")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Huyve")
                        .HasColumnName("huyve")
                        .HasColumnType("varchar(12)")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("Kenhgd")
                        .HasColumnName("kenhgd")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Ngaydi")
                        .HasColumnName("ngaydi")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnName("ngaytao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Ngayve")
                        .HasColumnName("ngayve")
                        .HasColumnType("date");

                    b.Property<string>("Nguoixuatve")
                        .HasColumnName("nguoixuatve")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Serial")
                        .HasColumnName("serial")
                        .HasColumnType("varchar(12)")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("Sgtcode")
                        .HasColumnName("sgtcode")
                        .HasColumnType("varchar(17)")
                        .HasMaxLength(17)
                        .IsUnicode(false);

                    b.Property<int?>("Sokhach")
                        .HasColumnName("sokhach")
                        .HasColumnType("int");

                    b.Property<string>("Tenkhach")
                        .HasColumnName("tenkhach")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Trangthai")
                        .HasColumnName("trangthai")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Stt");

                    b.ToTable("thongkewebchitiet");
                });

            modelBuilder.Entity("ThongKe.Data.Models.Tuyentheoquy", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Doanhso1")
                        .HasColumnName("doanhso1")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Doanhso11")
                        .HasColumnName("doanhso_1")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Doanhso2")
                        .HasColumnName("doanhso2")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Doanhso21")
                        .HasColumnName("doanhso_2")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Doanhso3")
                        .HasColumnName("doanhso3")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Doanhso31")
                        .HasColumnName("doanhso_3")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Sk1")
                        .HasColumnName("sk1")
                        .HasColumnType("int");

                    b.Property<int?>("Sk11")
                        .HasColumnName("sk_1")
                        .HasColumnType("int");

                    b.Property<int?>("Sk2")
                        .HasColumnName("sk2")
                        .HasColumnType("int");

                    b.Property<int?>("Sk21")
                        .HasColumnName("sk_2")
                        .HasColumnType("int");

                    b.Property<int?>("Sk3")
                        .HasColumnName("sk3")
                        .HasColumnType("int");

                    b.Property<int?>("Sk31")
                        .HasColumnName("sk_3")
                        .HasColumnType("int");

                    b.Property<string>("Tuyentq")
                        .HasColumnName("tuyentq")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Stt");

                    b.ToTable("tuyentheoquy");
                });

            modelBuilder.Entity("ThongKe.Data.Models.TuyentqNgayban", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int?>("Sokhach")
                        .HasColumnName("sokhach")
                        .HasColumnType("int");

                    b.Property<decimal?>("Thucthu")
                        .HasColumnName("thucthu")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<decimal?>("Tongtien")
                        .HasColumnName("tongtien")
                        .HasColumnType("decimal(12, 0)");

                    b.Property<string>("Tuyentq")
                        .HasColumnName("tuyentq")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Stt");

                    b.ToTable("tuyentqNgayban");
                });

            modelBuilder.Entity("ThongKe.Data.Models.TuyentqNgaydi", b =>
                {
                    b.Property<long>("Stt")
                        .HasColumnName("stt")
                        .HasColumnType("bigint");

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int?>("Khachcu")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("khachcu")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("Khachht")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("khachht")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Thucthucu")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("thucthucu")
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("Thucthuht")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("thucthuht")
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Tuyentq")
                        .HasColumnName("tuyentq")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Stt")
                        .HasName("PK_tuyentqNgaydi_1");

                    b.ToTable("tuyentqNgaydi");
                });

            modelBuilder.Entity("ThongKe.Data.Models.Users", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Chinhanh")
                        .HasColumnName("chinhanh")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Daily")
                        .HasColumnName("daily")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Doimatkhau")
                        .HasColumnName("doimatkhau")
                        .HasColumnType("bit");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnName("hoten")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Khoi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("khoi")
                        .HasColumnType("varchar(5)")
                        .HasDefaultValueSql("('OB')")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Ngaycapnhat")
                        .HasColumnName("ngaycapnhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Ngaydoimk")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ngaydoimk")
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Ngaytao")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ngaytao")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nguoicapnhat")
                        .HasColumnName("nguoicapnhat")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nguoitao")
                        .HasColumnName("nguoitao")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nhom")
                        .HasColumnName("nhom")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Role")
                        .HasColumnName("role")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<bool>("Trangthai")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("trangthai")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ThongKe.Models.KhachHuy", b =>
                {
                    b.Property<long>("stt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("batdau")
                        .HasColumnType("datetime2");

                    b.Property<string>("chinhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dailyhuyve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("giatour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ketthuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayhuyve")
                        .HasColumnType("datetime2");

                    b.Property<string>("nguoihuyve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sgtcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenkhach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuyentq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vetourid")
                        .HasColumnType("int");

                    b.HasKey("stt");

                    b.ToTable("KhachHuys");
                });

            modelBuilder.Entity("ThongKe.Models.TourBySGTCodeViewModel", b =>
                {
                    b.Property<string>("sgtcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("batdau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ketthuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("tuyentq")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sgtcode");

                    b.ToTable("TourBySGTCodeViewModels");
                });

            modelBuilder.Entity("ThongKe.Models.TuyenThamQuanViewModel", b =>
                {
                    b.Property<string>("tuyentq")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("tuyentq");

                    b.ToTable("Tuyentq");
                });

            modelBuilder.Entity("ThongKe.Models.TuyentqChiTietViewModel", b =>
                {
                    b.Property<long>("stt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("batdau")
                        .HasColumnType("datetime2");

                    b.Property<string>("chinhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dailyxuatve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("doanhthu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ketthuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("sgtcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sk")
                        .HasColumnType("int");

                    b.Property<string>("tuyentq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vetourid")
                        .HasColumnType("int");

                    b.HasKey("stt");

                    b.ToTable("TuyentqChiTietViewModels");
                });
#pragma warning restore 612, 618
        }
    }
}
